# Generated by Django 4.1.7 on 2023-02-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('eq_number', models.IntegerField()),
                ('rent_price', models.FloatField()),
                ('time_rent_start', models.DateTimeField(blank=True, null=True)),
                ('time_rent_end', models.DateTimeField(blank=True, null=True)),
                ('is_busy', models.BooleanField(default=False)),
            ],
        ),
    ]
