# Generated by Django 4.1.7 on 2023-03-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipclub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('eq_number', models.IntegerField()),
                ('rent_price', models.FloatField()),
                ('time_rent_start', models.CharField(default=0, max_length=255)),
                ('time_rent_end', models.CharField(default=0, max_length=255)),
                ('is_busy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('hour_rent', models.IntegerField()),
                ('hour_sum', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
