# Generated by Django 4.1.7 on 2023-03-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipclub', '0003_remove_equipclub_rent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipclub',
            name='rent_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
