# Generated by Django 4.1.7 on 2023-03-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipclub', '0007_rename_hour_rent_userrent_last_hour_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipclub',
            name='rent_price',
            field=models.FloatField(default=0),
        ),
    ]
