# Generated by Django 4.1.7 on 2023-03-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipclub', '0008_alter_equipclub_rent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrent',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrent',
            name='hour_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrent',
            name='last_hour_rent',
            field=models.IntegerField(default=0),
        ),
    ]
