# Generated by Django 4.1.7 on 2023-03-03 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipclub', '0009_alter_userrent_discount_alter_userrent_hour_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrent',
            name='discount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userrent',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
