# Generated by Django 4.1.7 on 2023-03-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipclub', '0010_alter_userrent_discount_alter_userrent_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrent',
            old_name='user_id',
            new_name='user',
        ),
    ]
