# Generated by Django 4.1.7 on 2023-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipclub', '0011_rename_user_id_userrent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrent',
            name='discount',
            field=models.FloatField(default=1),
        ),
    ]
